name: Runtime checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  hooks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.12'
      - run: python -m unittest discover -s tests -v
